<?php

namespace ContainerASCF90x;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTodo2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.df3OfTW.App\Entity\Todo' shared service.
     *
     * @return \App\Entity\Todo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.df3OfTW": it needs an instance of "App\\Entity\\Todo" but this type has been excluded in "config/services.yaml".');
    }
}
