<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCfslQGI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCfslQGI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCfslQGI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCfslQGI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCfslQGI\App_KernelDevDebugContainer([
    'container.build_hash' => 'CfslQGI',
    'container.build_id' => '6274cc8c',
    'container.build_time' => 1695833946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCfslQGI');
